<a href="https://colab.research.google.com/github/Tretlaw/Machine-Learning-/blob/main/Deep_Learning_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import random

#MNIST Dataset
from tensorflow.keras.datasets import mnist

#Model
from tensorflow.keras.models import Sequential

#Layers
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

from tensorflow.keras.utils import to_categorical


In [5]:
#Load data
 (x_train, y_train), (x_test, y_test) = mnist.load_data()

# Preprocess data

In [6]:
#Normalize the pixel values
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

#OneHotEncoder
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

#Add Channel dimension for Conv2D
x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)



# **Building the Neural networks**

In [7]:
model = Sequential()

#layer 1
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(MaxPooling2D(2,2))

#Layer 2
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(2,2))

#layer 3
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(2,2))

#layer 4
model.add(Flatten())
model.add(Dense(128, activation='relu'))

#layer 5
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

# Compile the model

In [8]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model

In [9]:
# epochs = 20
# batch_size =  128

#Train model
model.fit(x_train, y_train, epochs=20, batch_size=128, validation_split=0.1)

Epoch 1/20
422/422 [==============================] - 32s 72ms/step - loss: 0.4191 - accuracy: 0.8692 - val_loss: 0.0879 - val_accuracy: 0.9750
Epoch 2/20
422/422 [==============================] - 30s 70ms/step - loss: 0.1319 - accuracy: 0.9620 - val_loss: 0.0699 - val_accuracy: 0.9770
Epoch 3/20
422/422 [==============================] - 30s 72ms/step - loss: 0.0931 - accuracy: 0.9728 - val_loss: 0.0510 - val_accuracy: 0.9850
Epoch 4/20
422/422 [==============================] - 28s 67ms/step - loss: 0.0757 - accuracy: 0.9773 - val_loss: 0.0529 - val_accuracy: 0.9833
Epoch 5/20
422/422 [==============================] - 29s 69ms/step - loss: 0.0606 - accuracy: 0.9822 - val_loss: 0.0406 - val_accuracy: 0.9878
Epoch 6/20
422/422 [==============================] - 29s 68ms/step - loss: 0.0535 - accuracy: 0.9843 - val_loss: 0.0398 - val_accuracy: 0.9890
Epoch 7/20
422/422 [==============================] - 30s 70ms/step - loss: 0.0457 - accuracy: 0.9864 - val_loss: 0.0344 - val_accuracy:

# Evaluate the Model

In [10]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test LOss: {loss: .4f}, Test accuracy: {accuracy: .4f}')

313/313 [==============================] - 2s 6ms/step - loss: 0.0516 - accuracy: 0.9894
Test LOss:  0.0516, Test accuracy:  0.9894


# Make Predictions

In [12]:
predictions = model.predict(x_test[:8])
predicted_labels = np.argmax(predictions, axis=1)

print('Predicted Label: ', predicted_labels)
print('True Label: ', y_test[:8])

1/1 [==============================] - 0s 22ms/step
Predicted Label:  [7 2 1 0 4 1 4 9]
True Label:  [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
