<a href="https://colab.research.google.com/github/Tretlaw/Machine-Learning-/blob/main/Feature_Extraction_%26_Selection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler


In [45]:
dataX = [[20, 0.3], [30, 0.2], [10, 0.9], ]
scaler = MinMaxScaler()

scaled_data = scaler.fit_transform(dataX)

scaled_data

array([[0.5       , 0.14285714],
       [1.        , 0.        ],
       [0.        , 1.        ]])

In [46]:
bins = np.linspace(1, 6, 4)

bined_data = np.digitize(dataX, bins )

bined_data

array([[4, 0],
       [4, 0],
       [4, 0]])

In [47]:
from sklearn.preprocessing import PolynomialFeatures


dataY = [[2, 3], [2, 5], [1, 4], [5, 3]]
# puts data in form of a non linear equation.. according to the degree given (i.e degree=2, X**2 + 2X + 1 )
poly = PolynomialFeatures(degree=3)

poly_data = poly.fit_transform(dataY)
poly_data

array([[  1.,   2.,   3.,   4.,   6.,   9.,   8.,  12.,  18.,  27.],
       [  1.,   2.,   5.,   4.,  10.,  25.,   8.,  20.,  50., 125.],
       [  1.,   1.,   4.,   1.,   4.,  16.,   1.,   4.,  16.,  64.],
       [  1.,   5.,   3.,  25.,  15.,   9., 125.,  75.,  45.,  27.]])

In [48]:
from sklearn.preprocessing import OneHotEncoder
#OneHotEncoder assigns each categorical value a binary digit

colorData = [['Red'], ['Green'], ['Blue'], ['Violet']]

encoder = OneHotEncoder()

onehot_data = encoder.fit_transform(colorData).toarray()

onehot_data

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [49]:
from sklearn.preprocessing import LabelEncoder
#LabelEncoder assigns each categorical value a number

labelData = ['Low', 'High', 'Medium', 'High', 'Low']

encoder = LabelEncoder()

labeled_data = encoder.fit_transform(labelData)

labeled_data

array([1, 0, 2, 0, 1])

In [50]:
# Frequency encoding replaces the categorical data with the frequency in the data set
dataSeries = pd.Series(['Mark', 'Walter', 'Paul', 'Keith', 'Mark', 'Martha', 'Keith', 'Mark'])

frequency = dataSeries.value_counts(normalize=True)

encodeSeries = dataSeries.map(frequency)

encodeSeries


0    0.375
1    0.125
2    0.125
3    0.250
4    0.375
5    0.125
6    0.250
7    0.375
dtype: float64

In [51]:
#CountVectorizer counts the number if occurences of a word in the data
from sklearn.feature_extraction.text import CountVectorizer

textData = ['How are you', 'Are you okay', 'That is okay', 'I am okay', 'How are you doing']

vector = CountVectorizer()

textExtract = vector.fit_transform(textData)

text = textExtract.todense()

text

matrix([[0, 1, 0, 1, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 1, 0, 1],
        [0, 0, 0, 0, 1, 1, 1, 0],
        [1, 0, 0, 0, 0, 1, 0, 0],
        [0, 1, 1, 1, 0, 0, 0, 1]])

In [52]:
#TfidfVectorizer counts the number if occurences of a word in the data and forms a matrix according to the rarity of the word
from sklearn.feature_extraction.text import TfidfVectorizer

textData2 = ['How are you', 'Are you okay', 'That is okay', 'I am okay', 'How are you doing']

vector2 = TfidfVectorizer()

textExtract2 = vector2.fit_transform(textData2)

text2 = textExtract2.todense()

text2

matrix([[0.        , 0.53828256, 0.        , 0.64846263, 0.        ,
         0.        , 0.        , 0.53828256],
        [0.        , 0.57735027, 0.        , 0.        , 0.        ,
         0.57735027, 0.        , 0.57735027],
        [0.        , 0.        , 0.        , 0.        , 0.63907044,
         0.42799292, 0.63907044, 0.        ],
        [0.83088075, 0.        , 0.        , 0.        , 0.        ,
         0.55645052, 0.        , 0.        ],
        [0.        , 0.41955892, 0.62647696, 0.50543767, 0.        ,
         0.        , 0.        , 0.41955892]])

In [53]:
import gensim
from gensim.models import Word2Vec

textData2 = [['How', 'are', 'you'], ['Are', 'you', 'okay'], ['That', 'is', 'okay'], ['How', 'are', 'you', 'doing']]

model = Word2Vec(textData2, min_count=1)

wordVec = model.wv['is']

wordVec

array([-8.7274825e-03,  2.1301615e-03, -8.7354420e-04, -9.3190884e-03,
       -9.4281426e-03, -1.4107180e-03,  4.4324086e-03,  3.7040710e-03,
       -6.4986930e-03, -6.8730675e-03, -4.9994122e-03, -2.2868442e-03,
       -7.2502876e-03, -9.6033178e-03, -2.7436293e-03, -8.3628409e-03,
       -6.0388758e-03, -5.6709289e-03, -2.3441375e-03, -1.7069972e-03,
       -8.9569986e-03, -7.3519943e-04,  8.1525063e-03,  7.6904297e-03,
       -7.2061159e-03, -3.6668312e-03,  3.1185520e-03, -9.5707225e-03,
        1.4764392e-03,  6.5244664e-03,  5.7464195e-03, -8.7630618e-03,
       -4.5171441e-03, -8.1401607e-03,  4.5956374e-05,  9.2636338e-03,
        5.9733056e-03,  5.0673080e-03,  5.0610625e-03, -3.2429171e-03,
        9.5521836e-03, -7.3564244e-03, -7.2703874e-03, -2.2653891e-03,
       -7.7856064e-04, -3.2161034e-03, -5.9258583e-04,  7.4888230e-03,
       -6.9751858e-04, -1.6249407e-03,  2.7443992e-03, -8.3591007e-03,
        7.8558037e-03,  8.5361041e-03, -9.5840869e-03,  2.4462664e-03,
      

In [54]:
#Image extraction and recognition

import cv2

image = cv2.imread('/content/wizzy.jpg', 0)

hog = cv2.HOGDescriptor()

hog_details = hog.compute(image)

hog_details

array([0.00408582, 0.0021625 , 0.16214848, ..., 0.09258842, 0.13576984,
       0.12663126], dtype=float32)

In [55]:
import tensorflow as tf
from tensorflow.keras.applications import VGG16

image = tf.keras.preprocessing.image.load_img('/content/wizzy.jpg', target_size=(224, 224))
image = tf.keras.preprocessing.image.img_to_array(image)
image = tf.keras.applications.vgg16.preprocess_input(image)
vgg_model = VGG16(weights='imagenet', include_top=False)
features = vgg_model.predict(np.expand_dims(image, axis=0))
features


1/1 [==============================] - 1s 723ms/step


array([[[[  0.        ,   0.        ,   0.        , ...,   7.211959  ,
            3.793161  ,   0.        ],
         [  0.        ,   0.        ,   0.        , ...,   0.        ,
            0.        ,   0.        ],
         [  0.        ,   0.        ,   0.        , ...,   0.        ,
            0.        ,   0.        ],
         ...,
         [  0.        ,   0.        ,   0.        , ...,   0.        ,
            0.        ,   0.        ],
         [  0.        ,   0.        ,   0.        , ...,   0.        ,
            0.        ,   0.        ],
         [  0.        ,   0.        ,   0.        , ...,   0.        ,
            0.        ,   0.        ]],

        [[  0.        ,   0.        ,   0.        , ...,   0.        ,
            0.        ,   0.        ],
         [  0.        ,   0.        ,   0.        , ...,   0.        ,
            0.        ,   0.        ],
         [  0.        ,   0.        ,   0.        , ...,   0.        ,
            0.        ,   0.     